Write-Host "Installing VS Code extensions"
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension DotJoshJohnson.xml
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension johnpapa.Angular1
code --install-extension johnpapa.Angular2
code --install-extension Angular.ng-template
code --install-extension lukehoban.Go
code --install-extension mohsen1.prettify-json
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.mono-debug   
code --install-extension ms-vscode.PowerShell
code --install-extension ms-vscode.node-debug
code --install-extension vscjava.vscode-java-debug
code --install-extension ms-vscode.Theme-MarkdownKit    
code --install-extension ms-vscode.Theme-MaterialKit
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.debugger-for-edge
code --install-extension ms-vscode.vscode-azureextensionpack
code --install-extension PeterJausovec.vscode-docker